/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec;


import ru.clevertec.entity.Info;
import ru.clevertec.entity.MetaInfProduct;
import ru.clevertec.entity.Product;
import ru.clevertec.parser.Parser;


import ru.clevertec.parser.ParserI;


public class App {

    public static void main(String[] args) throws Exception {
        ParserI parserI = new Parser();

          Product product= new Product(1L, "Name", 12.1, 1L, 23.2);
          MetaInfProduct metaInfProduct = new MetaInfProduct(1L, true, new Info("name", 1));


        String json = parserI.generateJsonDefault(product);
        System.out.println("json = " + json);
        Object object = parserI.generateObjectFromJson(Product.class, json);
        System.out.println("object = " + object);

        String jsonM = parserI.generateJsonDefault(metaInfProduct);
        System.out.println("json = " + jsonM);
        Object objectM = parserI.generateObjectFromJson(MetaInfProduct.class, jsonM);
        System.out.println("object = " + objectM);

    }
}